/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4c5aaebe-2012-4dbd-b0dc-1372ce4a2fb2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Pi0Tqm0b8",
    "aws_user_pools_web_client_id": "6noi90ql5j5ej0ft3211gr2i7o",
    "oauth": {}
};


export default awsmobile;
