export const LOAD_LOCAL_DATA = 'LOAD_LOCAL_DATA'
export const LOAD_LOCAL_DATA_FAIL = 'LOAD_LOCAL_DATA_FAIL'
export const LOAD_LOCAL_DATA_SUCCESS = 'LOAD_LOCAL_DATA_SUCCESS'

export const DELETE_LOCAL_DATA = 'DELETE_LOCAL_DATA'
export const DELETE_LOCAL_DATA_FAIL = 'DELETE_LOCAL_DATA_FAIL'
export const DELETE_LOCAL_DATA_SUCCESS = 'DELETE_LOCAL_DATA_SUCCESS'

export const SAVE_LOCAL_DATA = 'SAVE_LOCAL_DATA'
export const SAVE_LOCAL_DATA_FAIL = 'SAVE_LOCAL_DATA_FAIL'
export const SAVE_LOCAL_DATA_SUCCESS = 'SAVE_LOCAL_DATA_SUCCESS'
