import * as aT from './actionTypes'

export const confirmingUser = (email: string) => ({type: aT.CONFIRM_USER, payload: email})
export const confirmUserFail = (email: string) => ({type: aT.CONFIRM_USER_FAIL, payload: email})
export const confirmUserSuccess = (email: string) => ({type: aT.CONFIRM_USER_SUCCESS, payload: email})
export const deleteApiToken = () => ({type: aT.DELETE_API_TOKEN})
export const deleteAuthToken = () => ({type: aT.DELETE_AUTH_TOKEN})
export const fetchingUser = (email: string) => ({type: aT.FETCH_USER, payload: email})
export const fetchUserFail = (email: string) => ({type: aT.FETCH_USER_FAIL, payload: email})
export const fetchUserSuccess = (email: string) => ({type: aT.FETCH_USER_SUCCESS, payload: email})
export const loggingOut = () => ({type: aT.LOG_OUT})
export const registeringUser = (email: string) => ({type: aT.REGISTER_USER, payload: email})
export const registerUserFail = (email: string) => ({type: aT.REGISTER_USER_FAIL, payload: email})
export const registerhUserSuccess = (email: string) => ({type: aT.REGISTER_USER_SUCCESS, payload: email})
export const setApiToken = () => ({type: aT.SET_API_TOKEN})
export const signInFailed = () => ({type: aT.SIGN_IN_FAIL})
export const signInSuccessful = () => ({type: aT.SIGN_IN_SUCCESS})
export const signingIn = () => ({type: aT.SIGN_IN})
export const signUpFailed = () => ({type: aT.SIGN_UP_FAIL})
export const signUpSuccessful = () => ({type: aT.SIGN_UP_SUCCESS})
export const signingUp = () => ({type: aT.SIGN_UP})
export const updateUser = (payload: object) => ({type: aT.UPDATE_USER, payload})
